name: Say hello

on:
  push:
    branches:
      - develop

jobs:
  hello_world:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola midu!"
      - name: Dime la fecha
        run: date
      - name: Lista archivos
        run: ls -l
